### ISSUE TITLE
Getting incorrect port for API 

### ISSUE THREAD

**Issue by Falanger-debug** [databucket/databucket-server#108]
I use in configuration server port: 8090, but frontend uses 8080 for API.
![image](https://github.com/databucket/databucket-server/assets/69849796/c8981d11-c2db-4bde-a334-bcf1114abc4e)

**Comment by guptapratik10** [comment]
I also observed the same. I had to remove Jenkins from 8080 and run Databucket there.

**Comment by kslysz** [comment]
I've tried to reproduce it. It works on my computer. Maybe this is some corner case I can not repeat.

```
server:
  port: 8090
  servlet.context-path: /
```
![image](https://github.com/user-attachments/assets/482f44ce-cb86-481b-9848-4fe8c67fd3ce)
![image](https://github.com/user-attachments/assets/203e01e3-cd84-46a8-99d9-cd01898c3731)

**Comment by kslysz** [comment]
It seems to be overwritten by IntelliJ. It can be forced by adding property in the "Run/Debug Configurations".
![image](https://github.com/user-attachments/assets/440e5863-21d1-43ba-be30-b62d279600c6)
