### ISSUE TITLE
Release v3.5.0 jar asset builded with hardcoded origin set as localhost

### ISSUE THREAD

**Issue by FelipeJK** [databucket/databucket-server#114]
Release v3.5.0 jar asset builded with hardcoded origin set as localhost.

We used the [jar 3.5.0](https://github.com/databucket/databucket-server/releases/download/v.3.5.0/databucket-server-3.5.0.jar) from the release page. 

After start the application, we tried to log in, but we got a white screen instead of redirect to the databucket server home page.

Looking in the Dev Tools, we found in the **UrlBuilder.js** file, that the variable origin is hardcoded to localhost:
![origin_error_jar_3 5 0](https://github.com/user-attachments/assets/f29b1c7f-2490-4b60-acf0-9568107e524e)

This behavior is not presented in the source code, only in the generated jar asset.
```
export const getOrigin = () => {
    const origin = window.location.origin;
    return origin + getContextPath();
}
```
Could you please generate the jar again?

Thanks for your support.

**Comment by kslysz** [comment]
fixed in v.3.5.1

**Comment by FelipeJK** [comment]
Thanks @kslysz !
