### ISSUE TITLE
Question: Is it possible to display a column value as a valid JSON formatted string

### ISSUE THREAD

**Issue by FelipeJK** [databucket/databucket-server#116]
We are using databucket-server and we have a column named as "Valor", where we store a JSON value.
![image](https://github.com/user-attachments/assets/6181c49f-d73e-453d-91f8-06cb55b84a63)

We would like to copy the json value and use it without the need to remove the escape character `\`.

Is it currently possible?

**Comment by kslysz** [comment]
Currently, this is not possible.
