### ISSUE TITLE
About data initialization

### ISSUE THREAD

**Issue by mrliudeveloper** [databucket/databucket-server#44]
Hello, kslysz! I think DataBuckets solves some of my problems, so I need to know exactly what DataBuckets does, but I think if there is some initialization data that makes it more intuitive, I would like you to provide some initialization data!

**Comment by kslysz** [comment]
Yes, I agree. For now, you can register to DEMO projekt and see some example data (https://databucket.pl/demo)

**Comment by mrliudeveloper** [comment]
Ok, thank you.I tried, but it kept saying "I have a problem with sending messages to the given email address!"  I have used QQ mailbox, Aliyun mailbox and Gmail, all of which are the same problem .

**Comment by kslysz** [comment]
Right, I see :( Google have changed configuration on target account. But, I've created the user for you manualy. Can you send me your contact directly on this email (databucket.info@gmail.com)?
I'll send you login and password.
